export default {
  NevishLineHex: {
    id: 1,
    hex: 'NevishLineHex',
    name: 'NevishLine',
    title: 'Nevish Line',
    col: 0,
    row: 3,
    points:
      {
        a : '',
        b : '',
        c : '',
        d : '',
        e : '',
        f : '',
        g : '',
        h : '',
        i : '',
        j : '',
        k : '',
        l : '',
        m : '',
        n : '',
        o : '',
        p : '',
        q : '',
        r : '',
        s : '',
        t : '',
        u : '0 0.5',
        v : '1 0.5',
        w : '1 0',
        x : '1 1',
        y : '0 1',
        z : '0 0'
      },
      areas: {

      }
  },
  OarbreakerHex: {
    col: 0,
    row: 5,
    points:
      {
        a : '',
        b : '',
        c : '',
        d : '',
        e : '',
        f : '',
        g : '',
        h : '',
        i : '',
        j : '',
        k : '',
        l : '',
        m : '',
        n : '',
        o : '',
        p : '',
        q : '',
        r : '',
        s : '',
        t : '',
        u : '0 0.5',
        v : '1 0.5',
        w : '1 0',
        x : '1 1',
        y : '0 1',
        z : '0 0'
      },
      areas: {

      }
  },
  FishermansRowHex: {
    col: 0,
    row: 7,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  OriginHex: { 
    col: 0, 
    row: 9 ,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  CallumsCapeHex: { 
    col: 1, 
    row: 2,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    } 
  },
  StonecradleHex: { 
    col: 1, 
    row: 4,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    } 
  },
  FarranacCoastHex: { 
    col: 1, 
    row: 6,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    } 
  },
  WestgateHex: { 
    col: 1, 
    row: 8,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    } 
  },
  AshFieldsHex: { 
    col: 1, 
    row: 10,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    } 
  },
  SpeakingWoodsHex: { 
    col: 2, 
    row: 1,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    } 
  },
  MooringCountyHex: { 
    col: 2, 
    row: 3,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    } 
  },
  LinnMercyHex: { 
    col: 2, 
    row: 5,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    } 
  },
  LochMorHex: { 
    col: 2, 
    row: 7,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  HeartlandsHex: { 
    col: 2, 
    row: 9,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  RedRiverHex: { 
    col: 2, 
    row: 11,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  BasinSionnachHex: { 
    col: 3, 
    row: 0,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  ReachingTrailHex: { 
    col: 3, 
    row: 2 ,
    points: {
      a : '0.568 0',
      b : '0.641 0',
      c : '0.898 0.298',
      d : '0.875 0.749',
      e : '0.594 1',
      f : '0.213 0.927',
      g : '0.095 0.695',
      h : '',
      i : '',
      j : '0.152 0.199',
      k : '0.298 0.322',
      l : '0.491 0.500',
      m : '0.548 0.475',
      n : '0.594 0.513',
      o : '0.769 0.463',
      p : '0.824 0.720',
      q : '0.684 0.685',
      r : '0.557 0.837',  
      s : '0.486 0.781',
      t : '0.414 0.601',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: 
    {
      "Brodytown" : 'k l m b a',
      "Dwyerstown" : 'g k j u',
      "Elksford" : 'g t l k',
      "Fort Mac Conaill" : 'x d p q r e',
      "Harpy" : 'e r s f y',
      "Ice Ranch" : 'b w c o n m',
      "Limestone Holdfast" : 'j k a z',
      "Mousetrap" : 'c v d p o',
      "Nightchurch" : 's t g f',
      "Reprieve" : 's r q n m l t',
      "The Ark" : 'n o p q',
    }
  },
  CallahansPassageHex: { 
    col: 3,
    row: 4,
    points:
    {
      a: '0.250 0',
      b: '0.703 0',
      c: '0.924 0.340',
      d: '0.955 0.598',
      e: '0.663 1',
      f: '0.297 1',
      g: '0.060 0.626',
      h: '0.364 0.312',
      i: '0.620 0.264',
      j: '0.669 0.353',
      k: '0.640 0.546',
      l: '0.626 0.551',
      m: '0.610 0.796',
      n: '0.432 0.686',
      o: '0.414 0.620',
      p: '0.458 0.512',
      q: '',
      r: '',
      s: '',
      t: '',
      u: '',
      v: '0 0.5',
      w: '0 1',
      x: '1 1',
      y: '1 0.5',
      z: '1 0'
    },
    areas: {
      'Cragstown' : 'a b i h ',
      'White Chapel' : 'b z c j i',
      'The Procession': 'j c y d k',
      'The Latch' : 'd k l m e x',
      'Lochan Berth' : 'h i j k l p',
      'Overlook Hill' : 'l p o n m',
      'The Crumbling Passage' : 'e f n m',
      'Crumbling Post' : 'f w g o n',
      'Scath Passing' : 'g o p h',
      'Solas Gorge' : 'g h a v'
    }
  },
  DeadLandsHex: {
    col: 3, 
    row: 6, 
    points :
    {
      a: '0.1 0',
      b: '0 0.318',
      c: '0.29 0.4',
      d: '0.375 0.36',
      e: '0.411 0',
      f: '0.475 0.39',
      g: '0.625 0.31',
      h: '0.666 0.328',
      i: '1 0.098',
      j: '0.9 0',
      k: '0.345 0.631',
      l: '0.481 0.540',
      m: '0.607 0.639',
      n: '0.687 0.556',
      o: '0.98 0.717',
      p: '0.579 0.738',
      q: '0.661 1',
      r: '1 1',
      s: '0.391 0.731',
      t: '0.266 1',
      u: '0 1',
      v: '0 0.69'
    },
    areas: {
      "The Spine": "a b c d e",
      "Iron's End": "e d f g",
      "Callahan's Gate": "e g h i j",
      "Abandoned Ward": "c d f l k",
      "Callahan's Boot" : "l f g h n m",
      "The Salt March" : "n h i o",
      "Brine Glen" : "m n o r q p",
      "The Pits" : "s k l m p",
      "The Salt Farms": "s p q t",
      "Sun's Hollow": "k s t u v",
      "Liberation Point": "b c k v"
    }
  },
  UmbralWildwoodHex: { 
    col: 3,
    row: 8,
    points:  {
      a: '0.356 0',
      b: '0.607 0',
      c: '0.846 0.198',
      d: '0.964 0.433',
      e: '0.858 0.882',
      f: '0.516 1',
      g: '0.153 0.806',
      h: '0.094 0.312',
      i: '0.224 0.396',
      j: '0.420 0.332',
      k: '0.447 0.351',
      l: '0.587 0.223',
      m: '0.727 0.304',
      n: '0.703 0.470',
      o: '0.731 0.488',
      p: '0.519 0.499',
      q: '0.500 0.597',
      r: '0.458 0.643',
      s: '0.273 0.690',
      t: '0.846 0',
      u: '1 0.433',
      v: '1 1',
      w: '0 1',
      x: '-0.01 0.5',
      y: '0 0',
      z: ''
    },
    areas: {
      'Vagrant Bastion': 'a b l k j',
      'Stray': 'b t c m l',
      'Amethyst': 'c m n o d',
      "Lachesis' Tally": 'd u v e o',
      'Hermits Rest': 'n o e q p',
      "Clotho's Refuge": 'k l m n p',
      "Atropos' Fate": 'f r q e v',
      'Sentry': 'g s r f w',
      'Golden Root Ranch': 'g s i h x',
      'The Foundry': 'a j i h y',
      'Thunderfoot': 'i j k p q r s'
    }
  },
  GreatMarchHex: { 
    col: 3, 
    row: 10 ,
    points:
      {
        a: '0.482 -0.01',
        b: '0.750 0.275',
        c: '0.668 0.368',
        d: '0.490 0.289',
        e: '0.464 0.221',
        f: '0.229 0.329',
        g: '0.409 0.535',
        h: '0.437 0.515',
        i: '0.367 0.663',
        j: '0.653 0.536',
        k: '0.784 0.932',
        l: '0.813 0.874',
        m: '0.142 0.786',
        n: '0.104 0.292',
        o: '0.870 0.244',
        p: '',
        q: '',
        r: '',
        s: '',
        t: '',
        u: '0.784 1',
        v: '0.142 1',
        w: '0 0.5',
        x: '0 0',
        y: '1 0.5',
        z: '1 0'
      },
      areas: {
        'Lionsfort': 'a b o z',
        'Dendro Field': 'o b c j l y',
        "Myrmidon's Stay": 'a b c d e',
        'Violethome': 'a e f n x',
        'Camp Senti': 'd e f g h',
        'Remnant Villa': 'c d h j',
        'Leto': 'g f n w m i',
        'Sitaria': 'j h g i k l',
        'The Swan': 'm i k u v'

      }
  },
  KalokaiHex: { 
    col: 3, 
    row: 12,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  HowlCountyHex: { 
    col: 4, 
    row: 1,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  ViperPitHex: { 
    col: 4,
    row: 3,
    points:
      {
        a : '0.759 0.022',
        b : '0.856 0.789',
        c : '0.583 1',
        d : '0.293 1',
        e : '0.08 0.66',
        f : '0.137 0.226',
        g : '0.414 0.484',
        h : '0.372 0.466',
        i : '0.239 0.68',
        j : '0.332 0.720',
        k : '0.464 0.684',
        l : '0.478 0.698',
        m : '0.678 0.538',
        n : '0.658 0.334',
        o : '0.759 0',
        p : '',
        q : '',
        r : '',
        s : '',
        t : '',
        u : '0 0.5',
        v : '1 0.5',
        w : '1 0',
        x : '1 1',
        y : '0 1',
        z : '0 0'
      },
      areas: {
        "Blackthroat" : 'c d j k l',
        "Earl Crowley" : 'a n m b v',
        "Fleck Crossing" : 'g n m l k',
        "Fort Viper" : 'i j k g h',
        "Kirknell" : 'e i h f u',
        "Moltworth" : 'b x c l m',
        "Serenity's Blight" : 'a n g h f z o',
        "The Friars" : 'd j i e y',
      }
  },
  MarbanHollow: { // no HEX in name, that's right!
    col: 4, 
    row: 5,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  }, 
  DrownedValeHex: { 
    col: 4,
    row: 7,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  ShackledChasmHex: { 
    col: 4,
    row: 9,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  AcrithiaHex: { 
    col: 4, 
    row: 11,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  ClansheadValleyHex: { 
    col: 5, 
    row: 2,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  WeatheredExpanseHex: { 
    col: 5, 
    row: 4,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  EndlessShoreHex: { 
    col: 5, 
    row: 6,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  AllodsBightHex: { 
    col: 5,
    row: 8,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  TerminusHex: { 
    col: 5, 
    row: 10,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  MorgensCrossingHex: { 
    col: 6, 
    row: 3,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  GodcroftsHex: { 
    col: 6, 
    row: 5,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  TempestIslandHex: { 
    col: 6, 
    row: 7,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  },
  TheFingersHex: { 
    col: 6, 
    row: 9,
    points:
    {
      a : '',
      b : '',
      c : '',
      d : '',
      e : '',
      f : '',
      g : '',
      h : '',
      i : '',
      j : '',
      k : '',
      l : '',
      m : '',
      n : '',
      o : '',
      p : '',
      q : '',
      r : '',
      s : '',
      t : '',
      u : '0 0.5',
      v : '1 0.5',
      w : '1 0',
      x : '1 1',
      y : '0 1',
      z : '0 0'
    },
    areas: {

    }
  }
};